### PR TITLE
Fix wrong player count in minecraftvanilla protocol

### LINKED ISSUE #162: Getting minecraft playercount always returns double of the actual playercount
Today I noticed that for minecraft using `players.length` always returned the wrong playercount.
I found out that it is always the actual playercount multiplied by 2 and found the source of the problem:
https://github.com/sonicsnes/node-gamedig/blob/master/protocols/minecraftvanilla.js#L50-L61
I guess you forgot to wrap the for loop in an else? @sonicsnes

### PR DESCRIPTION
**Pull request by P4sca1**
Closes #162

### CODE REVIEW

File: protocols/minecraftvanilla.js [hunk 1]
```diff
@@ -54,9 +54,10 @@ class MinecraftVanilla extends Core {
                     name: player.name
                 });
             }
-        }
-        for (let i = 0; i < Math.min(json.players.online, 10000); i++) {
-            state.players.push({});
+        } else {
+            for (let i = 0; i < Math.min(json.players.online, 10000); i++) {
```
Comment (sonicsnes) [inline protocols/minecraftvanilla.js]: Ah, I believe the original intention here was for i to be initialized to state.players.length. `sample` often doesn't include a full player list, so this loop is meant to fill out the rest of the slots with placeholders.

Comment (P4sca1) [reply protocols/minecraftvanilla.js]: Ah okay, I thought that when sample exists it always includes all players and otherwise we need to use placeholders.

Comment (P4sca1) [reply protocols/minecraftvanilla.js]: @sonicsnes I pushed another commit and also added coments to make this more clear.

**Comment by P4sca1** [comment]
@sonicsnes Anything else needed before releasing this fix?
